#!/usr/bin/env dart

import 'dart:io';

/// Quick setup script to configure Firebase with demo values for testing
void main() async {
  print('🔧 Setting up Firebase Demo Configuration...\n');

  // Demo Firebase configuration (these are safe placeholder values)
  const demoConfig = '''
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemo-Web-Key-Replace-With-Your-Actual-Key',
    appId: '1:123456789:web:demo-web-app-id',
    messagingSenderId: '123456789',
    projectId: 'whatsup-microlearning-demo',
    authDomain: 'whatsup-microlearning-demo.firebaseapp.com',
    storageBucket: 'whatsup-microlearning-demo.appspot.com',
    measurementId: 'G-DEMO123456',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemo-Android-Key-Replace-With-Your-Actual-Key',
    appId: '1:123456789:android:demo-android-app-id',
    messagingSenderId: '123456789',
    projectId: 'whatsup-microlearning-demo',
    storageBucket: 'whatsup-microlearning-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemo-iOS-Key-Replace-With-Your-Actual-Key',
    appId: '1:123456789:ios:demo-ios-app-id',
    messagingSenderId: '123456789',
    projectId: 'whatsup-microlearning-demo',
    storageBucket: 'whatsup-microlearning-demo.appspot.com',
    iosBundleId: 'com.example.whatsupMicrolearningBots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo-macOS-Key-Replace-With-Your-Actual-Key',
    appId: '1:123456789:macos:demo-macos-app-id',
    messagingSenderId: '123456789',
    projectId: 'whatsup-microlearning-demo',
    storageBucket: 'whatsup-microlearning-demo.appspot.com',
    iosBundleId: 'com.example.whatsupMicrolearningBots',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemo-Windows-Key-Replace-With-Your-Actual-Key',
    appId: '1:123456789:windows:demo-windows-app-id',
    messagingSenderId: '123456789',
    projectId: 'whatsup-microlearning-demo',
    authDomain: 'whatsup-microlearning-demo.firebaseapp.com',
    storageBucket: 'whatsup-microlearning-demo.appspot.com',
    measurementId: 'G-DEMO123456',
  );
}
''';

  try {
    // Write the demo configuration
    final file = File('lib/firebase_options.dart');
    await file.writeAsString(demoConfig);
    print('✅ Updated lib/firebase_options.dart with demo configuration');

    print('\n📋 Demo Configuration Summary:');
    print('   Project ID: whatsup-microlearning-demo');
    print('   Auth Domain: whatsup-microlearning-demo.firebaseapp.com');
    print('   Storage Bucket: whatsup-microlearning-demo.appspot.com');

    print('\n⚠️  IMPORTANT NOTES:');
    print('   • This is a DEMO configuration with placeholder values');
    print('   • Authentication will NOT work with real Firebase');
    print('   • You need to replace these with your actual Firebase values');
    print('   • Follow the FIREBASE_SETUP_GUIDE.md for proper setup');

    print('\n🚀 Next Steps:');
    print('   1. Run: flutter clean');
    print('   2. Run: flutter pub get');
    print('   3. Run: flutter run -d windows');
    print('   4. Test the app with demo authentication');
    print('   5. Follow FIREBASE_SETUP_GUIDE.md to set up real Firebase');

    print('\n✨ Demo setup complete!');
  } catch (e) {
    print('❌ Error setting up demo configuration: $e');
    exit(1);
  }
}
